d = open('C:/Program Files/KiCad/8.0/share/kicad/symbols/Device.kicad_sym', 'rb').read()
print('Device.kicad_sym: %d bytes' % len(d))
print('CRLF: %d' % d.count(b'\r\n'))
print('Bare LF: %d' % (d.count(b'\n') - d.count(b'\r\n')))
print('First 50 bytes:', d[:50])

m = open('C:/Program Files/KiCad/8.0/share/kicad/symbols/MCU_Module.kicad_sym', 'rb').read()
print('MCU_Module.kicad_sym: %d bytes' % len(m))
print('CRLF: %d' % m.count(b'\r\n'))
print('Bare LF: %d' % (m.count(b'\n') - m.count(b'\r\n')))
