c = open('C:/Users/DELL/my-board/my-board.kicad_sch').read()
i = c.find('(symbol\n\t\t(lib_id ')
print('First instance:', c[i:i+300] if i >= 0 else 'NOT FOUND')
i2 = c.find('(symbol\n\t\t(lib_id "MCU_Module')
print('ESP32 instance:', c[i2:i2+800] if i2 >= 0 else 'NOT FOUND')
w = c.find('(wire ')
print('Wires:', c[w:w+300] if w >= 0 else 'NOT FOUND')
s = c.find('(sheet_instances')
print('tail:', c[s:s+200] if s >= 0 else 'NOT FOUND')
print('last 200:', c[-200:])
